const std = @import("std");
const types = @import("types.zig");
const png = @import("../png.zig");
const tile = @import("../tile.zig");
const engine = @import("zamgba-engine");

pub const TilemapCodegenOptions = struct {
    map_name: []const u8 = "map",
    tileset_name: []const u8 = "tileset",
    bpp: png.BppMode = .bpp4,
    color_adjust: bool = false,
    no_palette: bool = false,
    no_tileset: bool = false,
};

pub const TilemapCodegenError = error{
    InvalidMetadata,
    NoLevelsFound,
    ImageDecodeError,
    TileSliceError,
    PaletteExtractError,
    WriteError,
    OutOfMemory,
    Unimplemented,
};

fn writeColorArray(writer: *std.Io.Writer, colors: []const u16, indent: []const u8) TilemapCodegenError!void {
    const ITEMS_PER_LINE: usize = 8;
    for (colors, 0..) |col, i| {
        if (i % ITEMS_PER_LINE == 0) {
            writer.writeAll(indent) catch return error.WriteError;
        }
        writer.print("0x{X:0>4}, ", .{col}) catch return error.WriteError;
        if (i % ITEMS_PER_LINE == (ITEMS_PER_LINE - 1) or i == colors.len - 1) {
            writer.writeAll("\n") catch return error.WriteError;
        }
    }
}

fn writeSinglePalette(writer: *std.Io.Writer, name: []const u8, pal: []const u16) TilemapCodegenError!void {
    writer.print("pub const {s}: [{}]u16 = [_]u16{{\n", .{ name, pal.len }) catch return error.WriteError;
    try writeColorArray(writer, pal, "    ");
    writer.writeAll("};\n\n") catch return error.WriteError;
}

fn writeBankedPalettes(writer: *std.Io.Writer, banks: *const [16][16]u16) TilemapCodegenError!void {
    writer.writeAll("pub const palette: [256]u16 = [_]u16{\n") catch return error.WriteError;
    for (banks, 0..) |bank, b_idx| {
        writer.print("    // Bank {}\n", .{b_idx}) catch return error.WriteError;
        try writeColorArray(writer, &bank, "    ");
    }
    writer.writeAll("};\n\npub const palettes: *const [16][16]u16 = @ptrCast(&palette);\n\n") catch return error.WriteError;
}

fn writePaletteResult(writer: *std.Io.Writer, pal_res: png.PaletteResult) TilemapCodegenError!void {
    switch (pal_res) {
        .bpp4 => |pal| try writeSinglePalette(writer, "palette", &pal),
        .bpp8 => |pal| try writeSinglePalette(writer, "palette", &pal),
        .bpp4x16 => |banks| try writeBankedPalettes(writer, &banks),
    }
}

fn writeTilesetData(
    writer: *std.Io.Writer,
    sliced_bytes: []const u8,
    tile_count: usize,
    bpp: png.BppMode,
) TilemapCodegenError!void {
    const is_8bpp = (bpp == .bpp8);
    const words_per_tile: usize = if (is_8bpp) 16 else 8;
    const type_name = if (is_8bpp) "engine.gfx2d.Tile8bpp" else "engine.gfx2d.Tile4bpp";
    const bytes_per_tile: usize = words_per_tile * @sizeOf(u32);

    writer.print("pub const tileset_tiles: [{}]{s} = [_]{s}{{\n", .{ tile_count, type_name, type_name }) catch return error.WriteError;
    for (0..tile_count) |t_idx| {
        const tile_slice = sliced_bytes[t_idx * bytes_per_tile .. (t_idx + 1) * bytes_per_tile];
        writer.writeAll("    [_]u32{ ") catch return error.WriteError;
        for (0..words_per_tile) |w_idx| {
            const word = std.mem.readInt(u32, tile_slice[w_idx * 4 .. (w_idx + 1) * 4][0..4], .little);
            writer.print("0x{X:0>8}, ", .{word}) catch return error.WriteError;
        }
        writer.writeAll("},\n") catch return error.WriteError;
    }
    writer.writeAll("};\n\n") catch return error.WriteError;
}

fn sanitizeIdentifier(allocator: std.mem.Allocator, name: []const u8) ![]u8 {
    const out = try allocator.alloc(u8, name.len);
    for (name, 0..) |c, i| {
        if (std.ascii.isAlphanumeric(c) or c == '_') {
            out[i] = c;
        } else {
            out[i] = '_';
        }
    }
    return out;
}

/// Generates Zig source code for ROM-resident GBA Mode 0 tilemap structures from parsed TilemapMetadata.
pub fn generateTilemapZigSource(
    allocator: std.mem.Allocator,
    metadata: *const types.TilemapMetadata,
    tileset_png_bytes: ?[]const u8,
    options: TilemapCodegenOptions,
) TilemapCodegenError![]u8 {
    if (metadata.levels.len == 0) {
        return error.NoLevelsFound;
    }

    var aw: std.Io.Writer.Allocating = .init(allocator);
    defer aw.deinit();
    const writer = &aw.writer;

    writer.writeAll("// Generated by zurag - DO NOT EDIT MANUALLY\n") catch return error.WriteError;
    writer.writeAll("const std = @import(\"std\");\n") catch return error.WriteError;
    writer.writeAll("const engine = @import(\"zamgba-engine\");\n") catch return error.WriteError;
    writer.writeAll("const hal = @import(\"zamgba-hal\");\n\n") catch return error.WriteError;

    writer.writeAll("pub const ScreenEntry = engine.ScreenEntry;\n") catch return error.WriteError;
    writer.writeAll("pub const MapLayerData = engine.MapLayerData;\n") catch return error.WriteError;
    writer.writeAll("pub const TileSet = engine.TileSet;\n\n") catch return error.WriteError;

    // Check if any level contains entity definitions
    var has_entities = false;
    for (metadata.levels) |lvl| {
        for (lvl.layers) |lyr| {
            if (lyr.entities.len > 0) {
                has_entities = true;
                break;
            }
        }
        if (has_entities) break;
    }

    if (has_entities) {
        writer.writeAll("pub const Entity = struct {\n") catch return error.WriteError;
        writer.writeAll("    identifier: []const u8,\n") catch return error.WriteError;
        writer.writeAll("    x: i32,\n") catch return error.WriteError;
        writer.writeAll("    y: i32,\n") catch return error.WriteError;
        writer.writeAll("    width: u32,\n") catch return error.WriteError;
        writer.writeAll("    height: u32,\n") catch return error.WriteError;
        writer.writeAll("};\n\n") catch return error.WriteError;
    }

    const has_tileset = (tileset_png_bytes != null and !options.no_tileset);
    if (has_tileset) {
        const png_bytes = tileset_png_bytes.?;
        const pal_res = png.extractPalette(png_bytes, .{
            .mode = options.bpp,
            .color_adjust = options.color_adjust,
        }) catch return error.PaletteExtractError;

        if (!options.no_palette) {
            try writePaletteResult(writer, pal_res);
        }

        var img = png.decompressIndexedPixels(allocator, png_bytes) catch return error.ImageDecodeError;
        defer img.deinit();

        var sliced = tile.sliceSpriteFrame(allocator, &img, .{
            .x = 0,
            .y = 0,
            .w = img.width,
            .h = img.height,
        }, options.bpp) catch return error.TileSliceError;
        defer sliced.deinit();

        try writeTilesetData(writer, sliced.bytes, sliced.tile_count, options.bpp);

        const bpp_union_field = if (options.bpp == .bpp8) "bpp8" else "bpp4";
        const pal_ref = if (!options.no_palette) "@ptrCast(&palette)" else "&.{}";
        writer.writeAll("pub const tileset: engine.TileSet = .{\n") catch return error.WriteError;
        writer.print("    .tiles = .{{ .{s} = &tileset_tiles }},\n", .{bpp_union_field}) catch return error.WriteError;
        writer.print("    .palette = {s},\n", .{pal_ref}) catch return error.WriteError;
        writer.writeAll("    .collision_masks = &[_]u16{},\n") catch return error.WriteError;
        writer.writeAll("};\n\n") catch return error.WriteError;
    }

    for (metadata.levels) |lvl| {
        const lvl_ident = sanitizeIdentifier(allocator, lvl.identifier) catch return error.OutOfMemory;
        defer allocator.free(lvl_ident);

        // Gather all entities in this level
        var total_level_entities: usize = 0;
        for (lvl.layers) |lyr| {
            total_level_entities += lyr.entities.len;
        }

        if (total_level_entities > 0) {
            writer.print("pub const {s}_entities: [{}]Entity = [_]Entity{{\n", .{ lvl_ident, total_level_entities }) catch return error.WriteError;
            for (lvl.layers) |lyr| {
                for (lyr.entities) |ent| {
                    writer.print("    .{{ .identifier = \"{s}\", .x = {}, .y = {}, .width = {}, .height = {} }},\n", .{
                        ent.identifier, ent.x, ent.y, ent.width, ent.height,
                    }) catch return error.WriteError;
                }
            }
            writer.writeAll("};\n\n") catch return error.WriteError;
        }

        for (lvl.layers) |lyr| {
            const lyr_ident = sanitizeIdentifier(allocator, lyr.identifier) catch return error.OutOfMemory;
            defer allocator.free(lyr_ident);

            if (lyr.collision_masks) |masks| {
                writer.print("pub const {s}_{s}_collision_masks: [{}]u16 = [_]u16{{\n", .{ lvl_ident, lyr_ident, masks.len }) catch return error.WriteError;
                for (masks, 0..) |mask, i| {
                    if (i % 8 == 0) {
                        writer.writeAll("    ") catch return error.WriteError;
                    }
                    writer.print("0x{X:0>4}, ", .{mask}) catch return error.WriteError;
                    if (i % 8 == 7 or i == masks.len - 1) {
                        writer.writeAll("\n") catch return error.WriteError;
                    }
                }
                writer.writeAll("};\n\n") catch return error.WriteError;
            }

            if (lyr.layer_type == .auto_layer or lyr.layer_type == .tiles or lyr.tiles.len > 0) {
                const total_cells = lyr.c_wid * lyr.c_hei;
                const entries = allocator.alloc(types.ParsedTileEntry, total_cells) catch return error.OutOfMemory;
                defer allocator.free(entries);

                for (entries) |*e| {
                    e.* = .{
                        .tile_id = 0,
                        .x = 0,
                        .y = 0,
                        .h_flip = false,
                        .v_flip = false,
                        .alpha = 1.0,
                    };
                }

                for (lyr.tiles) |t| {
                    if (t.x < lyr.c_wid and t.y < lyr.c_hei) {
                        const idx = @as(usize, t.y) * @as(usize, lyr.c_wid) + @as(usize, t.x);
                        entries[idx] = t;
                    }
                }

                writer.print("pub const {s}_{s}_entries: [{}]ScreenEntry = [_]ScreenEntry{{\n", .{ lvl_ident, lyr_ident, total_cells }) catch return error.WriteError;
                for (entries) |entry| {
                    writer.print("    .{{ .tile_index = {}, .h_flip = {}, .v_flip = {}, .palette_bank = 0 }},\n", .{
                        entry.tile_id,
                        entry.h_flip,
                        entry.v_flip,
                    }) catch return error.WriteError;
                }
                writer.writeAll("};\n\n") catch return error.WriteError;

                writer.print("pub const {s}_{s}_data: MapLayerData = .{{\n", .{ lvl_ident, lyr_ident }) catch return error.WriteError;
                writer.print("    .width = {},\n", .{lyr.c_wid}) catch return error.WriteError;
                writer.print("    .height = {},\n", .{lyr.c_hei}) catch return error.WriteError;
                if (has_tileset) {
                    writer.writeAll("    .tileset = &tileset,\n") catch return error.WriteError;
                } else {
                    writer.writeAll("    .tileset = null,\n") catch return error.WriteError;
                }
                writer.print("    .entries = &{s}_{s}_entries,\n", .{ lvl_ident, lyr_ident }) catch return error.WriteError;
                writer.writeAll("};\n\n") catch return error.WriteError;
            }
        }
    }

    return allocator.dupe(u8, aw.written()) catch return error.OutOfMemory;
}

// ====================================================================
// Unit Tests for Tilemap Code Generator (TDD Red Phase)
// ====================================================================

test "TMC001: Generate single layer map ScreenEntry ROM table" {
    const test_assets = @import("test_palettes");
    const tilemap = @import("../tilemap.zig");

    var meta = try tilemap.parseMetadata(std.testing.allocator, test_assets.ldtk_t01_intgrid, .auto);
    defer meta.deinit();

    const out = try generateTilemapZigSource(std.testing.allocator, &meta, null, .{
        .map_name = "test_level",
    });
    defer std.testing.allocator.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out, "pub const ScreenEntry = engine.ScreenEntry;") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const MapLayerData = engine.MapLayerData;") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const Level_0_IntGrid_entries: [") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, ".tile_index =") != null);
}

test "TMC002: Generate multi-layer map layer definitions and MapLayerData" {
    const test_assets = @import("test_palettes");
    const tilemap = @import("../tilemap.zig");

    var meta = try tilemap.parseMetadata(std.testing.allocator, test_assets.ldtk_t03_4bg, .auto);
    defer meta.deinit();

    const out = try generateTilemapZigSource(std.testing.allocator, &meta, null, .{
        .map_name = "multi_bg_map",
    });
    defer std.testing.allocator.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out, "Level_0_Grass_entries") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "Level_0_Platform_entries") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "Level_0_BigRock_entries") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "Level_0_Background_entries") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const Level_0_Grass_data: MapLayerData = .{") != null);
}

test "TMC003: Generate IntGrid collision masks table" {
    const test_assets = @import("test_palettes");
    const tilemap = @import("../tilemap.zig");

    var meta = try tilemap.parseMetadata(std.testing.allocator, test_assets.ldtk_t01_intgrid, .auto);
    defer meta.deinit();

    const out = try generateTilemapZigSource(std.testing.allocator, &meta, null, .{
        .map_name = "collision_level",
    });
    defer std.testing.allocator.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out, "pub const Level_0_IntGrid_collision_masks: [") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "0x0001") != null); // layer 0 bit
}

test "TMC004: Generate level entities array and typed declarations" {
    const test_assets = @import("test_palettes");
    const tilemap = @import("../tilemap.zig");

    var meta = try tilemap.parseMetadata(std.testing.allocator, test_assets.ldtk_t04_entities, .auto);
    defer meta.deinit();

    const out = try generateTilemapZigSource(std.testing.allocator, &meta, null, .{
        .map_name = "dungeon_entities",
    });
    defer std.testing.allocator.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out, "pub const Entity = struct {") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const Level_0_entities: [") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, ".identifier = \"Player\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, ".x = 48") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, ".y = 200") != null);
}

test "TMC005: Generate tile flip bitfields (h_flip, v_flip) in ScreenEntry" {
    const test_assets = @import("test_palettes");
    const tilemap = @import("../tilemap.zig");

    var meta = try tilemap.parseMetadata(std.testing.allocator, test_assets.ldtk_t05_flips, .auto);
    defer meta.deinit();

    const out = try generateTilemapZigSource(std.testing.allocator, &meta, null, .{
        .map_name = "flip_map",
    });
    defer std.testing.allocator.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out, ".h_flip = true") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, ".v_flip = true") != null);
}

test "TMC006: Generate complete map with tileset PNG and palette" {
    const test_assets = @import("test_palettes");
    const tilemap = @import("../tilemap.zig");

    var meta = try tilemap.parseMetadata(std.testing.allocator, test_assets.ldtk_t01_intgrid, .auto);
    defer meta.deinit();

    const out = try generateTilemapZigSource(std.testing.allocator, &meta, test_assets.png_pal16, .{
        .map_name = "full_map",
        .bpp = .bpp4,
    });
    defer std.testing.allocator.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out, "pub const palette: [16]u16 = [_]u16{") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const tileset_tiles: [") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const tileset: engine.TileSet = .{") != null);
}

test "TMC007: Reject invalid or empty tilemap metadata" {
    var empty_meta = types.TilemapMetadata{
        .arena = std.heap.ArenaAllocator.init(std.testing.allocator),
        .levels = &.{},
    };
    defer empty_meta.deinit();

    try std.testing.expectError(
        error.NoLevelsFound,
        generateTilemapZigSource(std.testing.allocator, &empty_meta, null, .{}),
    );
}

test "TMC008: Sanitize identifier replaces spaces, dashes, and special characters" {
    const raw_name = "Level 1 - Forest Zone! #1";
    const sanitized = try sanitizeIdentifier(std.testing.allocator, raw_name);
    defer std.testing.allocator.free(sanitized);

    try std.testing.expectEqualStrings("Level_1___Forest_Zone___1", sanitized);

    const punctuation_name = "layer.bg-sub/v1.0@final";
    const sanitized_punc = try sanitizeIdentifier(std.testing.allocator, punctuation_name);
    defer std.testing.allocator.free(sanitized_punc);

    try std.testing.expectEqualStrings("layer_bg_sub_v1_0_final", sanitized_punc);

    // Test codegen output with identifiers containing spaces & symbols
    var meta = types.TilemapMetadata{
        .arena = std.heap.ArenaAllocator.init(std.testing.allocator),
        .levels = &[_]types.ParsedLevel{
            .{
                .identifier = "World 1 - Stage 2 (Cave)",
                .world_x = 0,
                .world_y = 0,
                .px_wid = 256,
                .px_hei = 256,
                .layers = &[_]types.ParsedLayer{
                    .{
                        .identifier = "FG Layer / #1",
                        .layer_type = .tiles,
                        .grid_size = 8,
                        .c_wid = 2,
                        .c_hei = 2,
                        .tiles = &[_]types.ParsedTileEntry{
                            .{ .tile_id = 1, .x = 0, .y = 0, .h_flip = false, .v_flip = false, .alpha = 1.0 },
                        },
                    },
                },
            },
        },
    };
    defer meta.deinit();

    const out = try generateTilemapZigSource(std.testing.allocator, &meta, null, .{
        .map_name = "space_map",
    });
    defer std.testing.allocator.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out, "pub const World_1___Stage_2__Cave__FG_Layer____1_entries: [") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const World_1___Stage_2__Cave__FG_Layer____1_data: MapLayerData = .{") != null);
}

test "TMC009: Generate banked 16-bank 4-bpp palettes (4x16) in tilemap source" {
    const test_assets = @import("test_palettes");
    const tilemap = @import("../tilemap.zig");

    var meta = try tilemap.parseMetadata(std.testing.allocator, test_assets.ldtk_t01_intgrid, .auto);
    defer meta.deinit();

    const out = try generateTilemapZigSource(std.testing.allocator, &meta, test_assets.png_pal16, .{
        .map_name = "banked_map",
        .bpp = .bpp4x16,
    });
    defer std.testing.allocator.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out, "pub const palette: [256]u16 = [_]u16{") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "// Bank 0") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "// Bank 15") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const palettes: *const [16][16]u16 = @ptrCast(&palette);") != null);
}
