const std = @import("std");
const png = @import("png.zig");
const tile = @import("tile.zig");
const metadata = @import("metadata.zig");

pub const CodegenOptions = struct {
    sprite_name: []const u8 = "sprite",
    bpp: png.BppMode = .auto,
    color_adjust: bool = false,
    palette_only: bool = false,
    no_palette: bool = false,
};

pub const CodegenError = error{
    ImageDecodeError,
    MetadataParseError,
    TileSliceError,
    WriteError,
    OutOfMemory,
    Unimplemented,
};

/// Formats a flat slice of 16-bit GBA BGR555 colors as hex literals with 8 items per line.
fn writeColorArray(writer: *std.Io.Writer, colors: []const u16, indent: []const u8) CodegenError!void {
    for (colors, 0..) |col, i| {
        if (i % 8 == 0) {
            writer.writeAll(indent) catch return error.WriteError;
        }
        writer.print("0x{X:0>4}, ", .{col}) catch return error.WriteError;
        if (i % 8 == 7 or i == colors.len - 1) {
            writer.writeAll("\n") catch return error.WriteError;
        }
    }
}

/// Emits a single 1D palette definition: `pub const <name> = [_]u16{ ... };`
fn writeSinglePalette(writer: *std.Io.Writer, name: []const u8, pal: []const u16) CodegenError!void {
    writer.print("pub const {s} = [_]u16{{\n", .{name}) catch return error.WriteError;
    try writeColorArray(writer, pal, "    ");
    writer.writeAll("};\n") catch return error.WriteError;
}

/// Emits a 16-bank 2D palette definition: `pub const palettes = [16][16]u16{ ... };`
fn writeBankedPalettes(writer: *std.Io.Writer, banks: *const [16][16]u16) CodegenError!void {
    writer.writeAll("pub const palettes = [16][16]u16{\n") catch return error.WriteError;
    for (banks, 0..) |bank, b_idx| {
        writer.print("    [_]u16{{ // Bank {}\n", .{b_idx}) catch return error.WriteError;
        try writeColorArray(writer, &bank, "        ");
        writer.writeAll("    },\n") catch return error.WriteError;
    }
    writer.writeAll("};\n\npub const raw_palette: [256]u16 = @bitCast(palettes);\n") catch return error.WriteError;
}

/// Dispatches palette emission based on the PaletteResult variant.
fn writePaletteResult(writer: *std.Io.Writer, pal_res: png.PaletteResult) CodegenError!void {
    switch (pal_res) {
        .bpp4 => |pal| try writeSinglePalette(writer, "palette", &pal),
        .bpp8 => |pal| try writeSinglePalette(writer, "palette", &pal),
        .bpp4x16 => |banks| try writeBankedPalettes(writer, &banks),
    }
}

/// Generates full, type-safe Zig source code from PNG and JSON asset bytes.
pub fn generateZigSource(
    allocator: std.mem.Allocator,
    png_bytes: []const u8,
    json_bytes: ?[]const u8,
    options: CodegenOptions,
) CodegenError![]u8 {
    _ = json_bytes;

    // 1. Extract palette
    const pal_res = png.extractPalette(png_bytes, .{
        .mode = options.bpp,
        .color_adjust = options.color_adjust,
    }) catch return error.ImageDecodeError;

    // 2. Handle palette-only mode
    if (options.palette_only) {
        var aw: std.Io.Writer.Allocating = .init(allocator);
        defer aw.deinit();

        aw.writer.writeAll("// Generated by zurag - DO NOT EDIT MANUALLY\nconst std = @import(\"std\");\n\n") catch return error.WriteError;
        try writePaletteResult(&aw.writer, pal_res);

        return allocator.dupe(u8, aw.written()) catch return error.OutOfMemory;
    }

    return error.Unimplemented;
}

// ====================================================================
// Unit Tests for Code Generator (TDD Red Phase)
// ====================================================================

test "GEN001: generateZigSource for palette-only mode" {
    const test_assets = @import("test_palettes");
    const out = try generateZigSource(std.testing.allocator, test_assets.png_pal16, null, .{
        .palette_only = true,
        .bpp = .bpp4,
    });
    defer std.testing.allocator.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out, "pub const palette = [_]u16{") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const frame_tiles") == null);
}

test "GEN002: generateZigSource full sprite with real flying broom asset" {
    const test_assets = @import("test_palettes");
    const out = try generateZigSource(std.testing.allocator, test_assets.png_broom, test_assets.json_broom, .{
        .sprite_name = "tsetseg_flying",
        .bpp = .bpp8,
    });
    defer std.testing.allocator.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out, "pub const width: u16 = 32;") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const height: u16 = 32;") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const frame_count: u16 = 8;") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const tile_count_per_frame: u16 = 16;") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "\"flying\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const frame_tiles") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const raw_tiles") != null);
}

test "GEN003: generateZigSource 4x16 banked mode syntax" {
    const test_assets = @import("test_palettes");
    const out = try generateZigSource(std.testing.allocator, test_assets.png_pal256, null, .{
        .palette_only = true,
        .bpp = .bpp4x16,
    });
    defer std.testing.allocator.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out, "pub const palettes = [16][16]u16{") != null);
}

test "GEN004: generateZigSource error when missing json in full sprite mode" {
    const test_assets = @import("test_palettes");
    try std.testing.expectError(error.MetadataParseError, generateZigSource(std.testing.allocator, test_assets.png_broom, null, .{
        .palette_only = false,
    }));
}

test "GEN005: generateZigSource with --no-palette omits palette definition" {
    const test_assets = @import("test_palettes");
    const out = try generateZigSource(std.testing.allocator, test_assets.png_broom, test_assets.json_broom, .{
        .sprite_name = "tsetseg_flying",
        .bpp = .bpp8,
        .no_palette = true,
    });
    defer std.testing.allocator.free(out);

    // Frame tiles are generated, but palette definition is omitted
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const frame_tiles") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const palette: [") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, ".palette = null") != null);
}
